// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface FlightI {
  flight_id: number;
  takeoff_date_time: number;
  takeoff_airport: string;
  landing_date_time: number;
  landing_airport: string;
  airplane_id: number;
}

// Generated by https://quicktype.io// Generated by https://quicktype.io

export interface SeatAssignedI {
  seat_id: number;
  seat_column: string;
  seat_row: number;
  seat_type_id: number;
  airplane_id: number;
}

export interface PassengerI {
  passenger_id: number;
  dni: string;
  name: string;
  age: number;
  country: string;
}

// Generated by https://quicktype.io

export interface BoardingPassI {
  boarding_pass_id: number;
  purchase_id: number;
  passenger_id: number;
  seat_type_id: number;
  seat_id: null;
  flight_id: number;
}
